name: Windows tests rust

on:
  - push
#  pull_request:
#    paths:
#      - 'polars/**'
jobs:
  test-rust:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-02-23
          override: true
      - name: Run tests
        run: |
          cargo clean
          cd polars && cargo clean && make test && make integration-tests
